name: OWASP ZAP Docker Scan

on:
  push:
    branches:
      - owasp

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run OWASP ZAP Docker Container
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-full-scan.py -t https://krishnagarg.cloud/ -r zap_report.html

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: OWASP ZAP Report
          path: zap_report.html
