name: OWASP Nettacker Scan

on:
  push:
    branches:
      - owasp

jobs:
  nettacker_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull OWASP Nettacker Docker Image
        run: docker pull owasp/nettacker

      - name: Run OWASP Nettacker Scan
        run: |
          docker run --rm -v /home/runner/work/Krishna-Web/Krishna-Web:/data owasp/nettacker python nettacker.py -i 'https://krishnagarg.cloud/' -o /data/nettacker_report.html -m all -L en

      - name: Upload OWASP Nettacker Report
        uses: actions/upload-artifact@v3
        with:
          name: OWASP Nettacker Report
          path: Krishna-Web/nettacker_report.html
