name: OWASP ZAP Scan

on:
  push:
    branches:
      - owasp

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'https://krishnagarg.cloud/'
          cmd_options: '-t https://krishnagarg.cloud/ -r zap_report.html' # Correctly format command options
          docker_name: 'owasp/zap2docker-weekly' # Correct image name
          issue_title: 'ZAP Full Scan Report'
          fail_action: false  # Optional: prevent the action from failing on minor issues
          allow_issue_writing: true  # Optional: allow writing issues to GitHub

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: OWASP ZAP Report
          path: zap_report.html
