name: OWASP Nettacker Scan

on:
  push:
    branches:
      - owasp

jobs:
  nettacker_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run OWASP Nettacker Scan
        run: |
          # Pull the OWASP Nettacker Docker image
          docker pull owasp/nettacker

          # Run OWASP Nettacker Docker container to install dependencies and perform the scan
          docker run --rm -v $(pwd):/data owasp/nettacker /bin/sh -c "\
            pip install multiprocess && \
            python nettacker.py -i https://krishnagarg.cloud/ -o /data/nettacker_report.html -m all -T 10 --silent"

      - name: Upload OWASP Nettacker Report
        uses: actions/upload-artifact@v3
        with:
          name: OWASP Nettacker Report
          path: nettacker_report.html
