name: Arachni Scan

on:
  push:
    branches:
      - main

jobs:
  arachni_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Arachni
        run: |
          sudo apt-get update
          sudo apt-get install arachni

      - name: Run Arachni Scan
        run: arachni https://krishnagarg.cloud/ --output-json=output.json
